/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MESSAGE_H_RPCGEN
#define _MESSAGE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct get_res {
	int value;
	int status;
};
typedef struct get_res get_res;

struct d_init_1_argument {
	char *name;
	int N;
};
typedef struct d_init_1_argument d_init_1_argument;

struct d_set_1_argument {
	char *name;
	int i;
	int value;
};
typedef struct d_set_1_argument d_set_1_argument;

struct d_get_1_argument {
	char *name;
	int i;
};
typedef struct d_get_1_argument d_get_1_argument;

#define NANODT 55555
#define NANODT_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define d_init 1
extern  enum clnt_stat d_init_1(char *, int , int *, CLIENT *);
extern  bool_t d_init_1_svc(char *, int , int *, struct svc_req *);
#define d_set 2
extern  enum clnt_stat d_set_1(char *, int , int , int *, CLIENT *);
extern  bool_t d_set_1_svc(char *, int , int , int *, struct svc_req *);
#define d_get 3
extern  enum clnt_stat d_get_1(char *, int , struct get_res *, CLIENT *);
extern  bool_t d_get_1_svc(char *, int , struct get_res *, struct svc_req *);
extern int nanodt_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define d_init 1
extern  enum clnt_stat d_init_1();
extern  bool_t d_init_1_svc();
#define d_set 2
extern  enum clnt_stat d_set_1();
extern  bool_t d_set_1_svc();
#define d_get 3
extern  enum clnt_stat d_get_1();
extern  bool_t d_get_1_svc();
extern int nanodt_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_get_res (XDR *, get_res*);
extern  bool_t xdr_d_init_1_argument (XDR *, d_init_1_argument*);
extern  bool_t xdr_d_set_1_argument (XDR *, d_set_1_argument*);
extern  bool_t xdr_d_get_1_argument (XDR *, d_get_1_argument*);

#else /* K&R C */
extern bool_t xdr_get_res ();
extern bool_t xdr_d_init_1_argument ();
extern bool_t xdr_d_set_1_argument ();
extern bool_t xdr_d_get_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MESSAGE_H_RPCGEN */
