/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "message.h"
#include "lib.h"

bool_t
d_add_1_svc(int a, int b, struct result *result,  struct svc_req *rqstp)
{
	(*result).status = add( &((*result).value), a, b) ; 

	return 1 ;
}

bool_t
d_divide_1_svc(int a, int b, struct result *result,  struct svc_req *rqstp)
{
	(*result).status = divide( &((*result).value), a, b) ; 

	return 1 ;
}

bool_t
d_neg_1_svc(int a, struct result *result,  struct svc_req *rqstp)
{
	(*result).status = neg( &((*result).value), a) ; 

	return 1 ;
}

int
calc_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	return 1;
}

