/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "message.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
d_add_1(int a, int b, struct result *clnt_res,  CLIENT *clnt)
{
	d_add_1_argument arg;
	arg.a = a;
	arg.b = b;
	return (clnt_call (clnt, d_add, (xdrproc_t) xdr_d_add_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
d_divide_1(int a, int b, struct result *clnt_res,  CLIENT *clnt)
{
	d_divide_1_argument arg;
	arg.a = a;
	arg.b = b;
	return (clnt_call (clnt, d_divide, (xdrproc_t) xdr_d_divide_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
d_neg_1(int a, struct result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, d_neg,
		(xdrproc_t) xdr_int, (caddr_t) &a,
		(xdrproc_t) xdr_result, (caddr_t) clnt_res,
		TIMEOUT));
}
