/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "message.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
d_init_1(char *name, int N, int *clnt_res,  CLIENT *clnt)
{
	d_init_1_argument arg;
	arg.name = name;
	arg.N = N;
	return (clnt_call (clnt, d_init, (xdrproc_t) xdr_d_init_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
d_set_1(char *name, int i, int value, int *clnt_res,  CLIENT *clnt)
{
	d_set_1_argument arg;
	arg.name = name;
	arg.i = i;
	arg.value = value;
	return (clnt_call (clnt, d_set, (xdrproc_t) xdr_d_set_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
d_get_1(char *name, int i, struct get_res *clnt_res,  CLIENT *clnt)
{
	d_get_1_argument arg;
	arg.name = name;
	arg.i = i;
	return (clnt_call (clnt, d_get, (xdrproc_t) xdr_d_get_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_get_res, (caddr_t) clnt_res,
		TIMEOUT));
}
