/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "message.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_d_init_1 (d_init_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (d_init_1_svc(argp->name, argp->N, result, rqstp));
}

int
_d_set_1 (d_set_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (d_set_1_svc(argp->name, argp->i, argp->value, result, rqstp));
}

int
_d_get_1 (d_get_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (d_get_1_svc(argp->name, argp->i, result, rqstp));
}

static void
nanodt_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		d_init_1_argument d_init_1_arg;
		d_set_1_argument d_set_1_arg;
		d_get_1_argument d_get_1_arg;
	} argument;
	union {
		int d_init_1_res;
		int d_set_1_res;
		struct get_res d_get_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case d_init:
		_xdr_argument = (xdrproc_t) xdr_d_init_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_d_init_1;
		break;

	case d_set:
		_xdr_argument = (xdrproc_t) xdr_d_set_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_d_set_1;
		break;

	case d_get:
		_xdr_argument = (xdrproc_t) xdr_d_get_1_argument;
		_xdr_result = (xdrproc_t) xdr_get_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_d_get_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!nanodt_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (NANODT, NANODT_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, NANODT, NANODT_VERSION, nanodt_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (NANODT, NANODT_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, NANODT, NANODT_VERSION, nanodt_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (NANODT, NANODT_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
