/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "message.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_d_add_1 (d_add_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (d_add_1_svc(argp->a, argp->b, result, rqstp));
}

int
_d_divide_1 (d_divide_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (d_divide_1_svc(argp->a, argp->b, result, rqstp));
}

int
_d_neg_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (d_neg_1_svc(*argp, result, rqstp));
}

static void
calc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		d_add_1_argument d_add_1_arg;
		d_divide_1_argument d_divide_1_arg;
		int d_neg_1_arg;
	} argument;
	union {
		struct result d_add_1_res;
		struct result d_divide_1_res;
		struct result d_neg_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case d_add:
		_xdr_argument = (xdrproc_t) xdr_d_add_1_argument;
		_xdr_result = (xdrproc_t) xdr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_d_add_1;
		break;

	case d_divide:
		_xdr_argument = (xdrproc_t) xdr_d_divide_1_argument;
		_xdr_result = (xdrproc_t) xdr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_d_divide_1;
		break;

	case d_neg:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_d_neg_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!calc_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALC, CALC_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALC, CALC_VERSION, calc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALC, CALC_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALC, CALC_VERSION, calc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALC, CALC_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
